# Generated by Django 4.0.5 on 2022-07-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=2089)),
            ],
        ),
    ]
